[tool.poetry]
name = "explainability_interpretability_robustness"
version = "0.1.0"
description = "Sandbox for explainability/interpretability/robustness technics/methods"
license = "Proprietary"
authors = ["Loïc Baret <baret.loic.1@gmail.com>"]
readme = "README.md"
keywords = [
    "explainability", "interpretability", "robustness", "machine learning", "deep learning"
]
packages = [
    { include = "src", from = "." }
]

[tool.poetry.scripts]
finetune_resnet = 'src.cli:pretrain_resnet'

[tool.poetry.dependencies]
python = "^3.10"
torch = "^1.12.1"
torchvision = "^0.13.1"
captum = "^0.5.0"
rich = "^12.5.1"
click = "^8.1.3"
pytorch-lightning = "^1.7.3"
notebook = "^6.4.12"

[tool.poetry.dev-dependencies]
ipykernel = "*"